stages:
  split:
    cmd: python src/data/split_data.py
    deps:
    - src/data/split_data.py
    - data/raw_data/raw.csv
    outs:
    - data/processed_data/X_train.csv
    - data/processed_data/X_test.csv
    - data/processed_data/y_train.csv
    - data/processed_data/y_test.csv
  normalize:
    cmd: python src/data/normalize_data.py
    deps:
    - src/data/normalize_data.py
    - data/processed_data/X_train.csv
    - data/processed_data/X_test.csv
    outs:
    - data/processed_data/X_train_scaled.csv
    - data/processed_data/X_test_scaled.csv
    - models/scaler.pkl
  gridsearch:
    cmd: python src/models/gridsearch.py
    deps:
    - src/models/gridsearch.py
    - data/processed_data/X_train_scaled.csv
    - data/processed_data/y_train.csv
    outs:
    - models/best_params.pkl
    - models/best_estimator_gridsearch.pkl
  train:
    cmd: python src/models/train_model.py
    deps:
    - src/models/train_model.py
    - data/processed_data/X_train_scaled.csv
    - data/processed_data/y_train.csv
    - models/best_params.pkl
    outs:
    - models/trained_model.pkl
  evaluate:
    cmd: python src/models/evaluate_model.py
    deps:
    - src/models/evaluate_model.py
    - data/processed_data/X_test_scaled.csv
    - data/processed_data/y_test.csv
    - models/trained_model.pkl
    outs:
    - data/predictions.csv
    metrics:
    - metrics/scores.json:
        cache: false
